name: deployment

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v3
    
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.0
    
            - name: Build
              run: |
                npm install
                npm run build:prod
    
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              id: deployment

    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source
    
        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        
        steps:
            - name: deployment
              id: deployment
              uses: actions/deploy-pages@v4
