name: deployment

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        uses: actions/setup-node@v3
        
      - name: Install packages & build
        run: |
          npm ci
          npm run build:prod

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          name: artifact
          overwrite: true
  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment: 
      name: github-pages
      
    permissions: 
      deployments: write
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: artifact