name: deployment

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v3
    
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.0
    
            - name: Build
              run: |
                npm install
                npm run build:prod
    
            - name: Deploy to Github Pages
              uses: actions/deploy-pages@v4
              id: deployment
